// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxeonzbCmDCV693T5hcI29RwRH0In-sk',
    appId: '1:123403823832:android:bd40c44bb70986335f05ad',
    messagingSenderId: '123403823832',
    projectId: 'backendamulet',
    storageBucket: 'backendamulet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXR7eKG4515jjwThOxzImkxViRo22WOoE',
    appId: '1:123403823832:ios:7b3612005f2837e85f05ad',
    messagingSenderId: '123403823832',
    projectId: 'backendamulet',
    storageBucket: 'backendamulet.firebasestorage.app',
    iosClientId: '123403823832-t1622f5c9g9vuajmnrd47ggjqm5qbbeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.amuletScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXR7eKG4515jjwThOxzImkxViRo22WOoE',
    appId: '1:123403823832:ios:7b3612005f2837e85f05ad',
    messagingSenderId: '123403823832',
    projectId: 'backendamulet',
    storageBucket: 'backendamulet.firebasestorage.app',
    iosClientId: '123403823832-t1622f5c9g9vuajmnrd47ggjqm5qbbeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.amuletScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJstgNSx4uN2CIhwIGqLPRLm7vZHFFqo8',
    appId: '1:123403823832:web:c8de38e8c364a16a5f05ad',
    messagingSenderId: '123403823832',
    projectId: 'backendamulet',
    authDomain: 'backendamulet.firebaseapp.com',
    storageBucket: 'backendamulet.firebasestorage.app',
    measurementId: 'G-CVP4JTBQ5M',
  );
}
